### PR TITLE
New names cleanup and potential bugfixes

### LINKED ISSUE #4791: units.cache gaining extra duplicates of refits and sometimes the entire unit database
### Environment
Windows 10 / Java 17 / 0.50.00 release

### Description
units.cache is receiving duplicates of refits when they are made. If units.cache is deleted to attempt resolution, units.cache recieves a duplicat of all BattleTech units (not just customs), doubling the file size the first time and increasing by the same amount each successive time, resulting in multiple duplicates of everything.
image
image
image
The 'Firebird' was a refit made before moving to 0.50.00, the (Food Truck) was made after, both are duplicated. Removing the units.cache and the mechfiles and even replacing the units.cache with one from another verified 'clean' installation seems ineffective.
### Files
[FOODIES.zip](https://github.com/user-attachments/files/16885492/FOODIES.zip)
[customs.zip](https://github.com/user-attachments/files/16885494/customs.zip)
[units.zip](https://github.com/user-attachments/files/16885498/units.zip)
The Units.cache file attached has duplicates of custom refits.

### PR DESCRIPTION
**Pull request by Setsul**
That should be the last of MekHQ updated to follow the new "IS name (clan name) model" naming scheme. MM and MML still have some bits.
Please excuse the funny list of commits, only [bd0e259](https://github.com/MegaMek/mekhq/pull/5043/commits/bd0e2599c8c294e150304c29ea57d8c1af0eac9c) is actually new.

This will prevent custom refits of clan units from reusing already taken model names. I don't think that bug was reported though.
The change from `loadMekData()` to `refreshUnitData()` might help with #4554 and potentially fix #4791 but I haven't tested either and the proper way for the former would still be to enable the (un)loading of a single specified file.

The rest is some incidental cleanup and refactoring to prepare for implementing #4978

### CODE REVIEW

**Review by IllianiCBT — APPROVED** [review]
How much testing has the cache portion of this had? The code looks fine, I’m just wary of exacerbating the existing refit issues.

**Comment by IllianiCBT** [comment]
Also, this is approved pending the JavaDoc error being fixed

**Comment by Setsul** [comment]
> How much testing has the cache portion of this had? The code looks fine, I’m just wary of exacerbating the existing refit issues.
"It works on my machine"
Not very extensive, but the few refits I've tried did show up and it didn't lag or freeze.
`refreshUnitData()` is used elsewhere so if it's broken we need to fix it anyway.

**Comment by IllianiCBT** [comment]
That was my assumption, but I’ve learned not to assume. When this gets merged let’s flag it with the QA folks so they know to test it, speaking of which I should probably give you to contributor role on Discord…

**Pull request merged**
