### PR TITLE
1971: Fixing Repair Bay Bonus Parts

### LINKED ISSUE #1971: 47.9 Bonus Part quantity not tracked properly on the Repair Bay Parts Acquisition menu
### Environment
47.9 (or 47.10-dev, issue appears in both versions)
Windows 10
Java version 1.8.0_261

### Description
While the Purchase Parts menu correctly displays the number of Bonus Parts currently available in an AtB campaign, the Parts Acquisition menu in the Repair Bay does not. 
image
image

(RBPA = Repair Bay Parts Acquisition, BP = Bonus Parts)
While I currently have BP available, I have also found it possible to use BP from the RBPA window past what should be possible. In the provided save, 7 parts needed for repairs are missing, and 10 BP are available. If you use the Purchase Parts menu to acquire 4-9 parts (I chose PPCs) simply to reduce the number of BP available, you can then use the RBPA to acquire all 7 missing parts anyway. When I tested this with the current save and MekHQ version, the displayed number of Bonus Parts available in the RBPA window stayed constant at -2, but I have also seen it increment to increasingly negative numbers on other occasions as parts were acquired using the RBPA window. Even closing the RBPA window and re-opening the Purchase Parts window partway through (to confirm that no further BP should be available) does not stop you from acquiring all missing parts in the RBPA window using BP. 

### Files
[Coppercoats.zip](https://github.com/MegaMek/mekhq/files/5133256/Coppercoats.zip)
No custom units or other files.

### PR DESCRIPTION
**Pull request by Windchild292**
This fixes #1971 and standardizes the bonus part code.

The first commit is a bunch of refactoring, continued by the actual fix.

### CODE REVIEW

**Review by NickAragua — APPROVED** [review]

**Comment by Windchild292** [comment]
@NickAragua any ideas on how to fix the CI failure? It appears to be related to adding resources to Campaign.

**Comment by NickAragua** [comment]
I'm seeing a bunch of failures in the StripUnitAction test

**Comment by Windchild292** [comment]
Yeah, because of MissingResourceException... so it can't get to the resource file required for Campaign.

**Comment by NickAragua** [comment]
Can you run the test locally?

**Comment by Windchild292** [comment]
I can.

**Comment by NickAragua** [comment]
My guess is that something is referencing the wrong resource file.

**Comment by Windchild292** [comment]
I wonder if that will fix it... it wasn't capitalized, while the Personnel ones are

**Comment by Windchild292** [comment]
It was the capitalization...

**Pull request merged**
