### PR TITLE
add export finances to CSV file, addresses feature request: #515

### PR DESCRIPTION
**Pull request by firefly2442**
add export finances to CSV file, fixes: #515

### CODE REVIEW

**Comment by pheonixstorm** [comment]
515 wasn't a bug so this doesn't "fix" anything, just adds a requested feature. Proper labeling is important ;)

**Comment by firefly2442** [comment]
Thanks, amended commit.

**Comment by wildj79** [comment]
Though this is a pretty simple addition, I think this feature deserves a little more discussion. Specifically whether we should be using a library to generate the `csv` file rather than rolling our own. @firefly2442 we'd like to invite you to our public slack. You can find a link to join on the http://megamek.org website under the "Community" tab.

**Comment by NickAragua** [comment]
To save some time, I believe it's http://megamek.org:3000

**Comment by firefly2442** [comment]
I'm going to work on this some more.  Closing.

**Pull request closed without merging**
