### PR TITLE
Campaign now uses pickRandomCamouflage when initialized

### LINKED ISSUE #5114: [RFE] Random Camo on New Campaign
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

In 50.01 we introduced a random camo picker for OpFor. It would be great for that functionality to be extended to the player-campaign when first entering Campaign Options (on a new campaign). This would likely need to be handled in CO IIC, but mentioning it in an issue report so it doesn't get forgotten,

### MekHQ Suite Version *

50.01

### Attach Files

_No response_

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

### PR DESCRIPTION
**Pull request by DM0000**
Modified pickRandomCamo to have "Root" faction that selects from all faction icons and implemented it in Campaign.

closes #5114

### CODE REVIEW

**Comment by DM0000** [comment]
Worked with all the start dates except the 3rd Jihad one but that one seems to be broken

**Comment by IllianiCBT** [comment]
What error does that give you?

**Comment by DM0000** [comment]
Campaign file could not be loaded.  Gives same error when I switch to master too.

**Comment by DM0000** [comment]
Also realize that maybe I should limit the camos to "Standard Camouflage" instead of all camos

**Comment by DM0000** [comment]
log error
16:11:30,946 ERROR [mekhq.gui.dialog.DataLoadingDialog] {AWT-EventQueue-0}
mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:436) - 
java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "7LA"

**Comment by IllianiCBT** [comment]
Perfect, we’re still tracking down the last of those from work that was done in 50.01. I’ll get that fixed in an hour

**Comment by DM0000** [comment]
Let me know if I should switch to just "Standard Camouflage" instead of all.

**Comment by IllianiCBT** [comment]
I think ‘all’ is perfectly fine. Gives a lot more choice and I don’t think anyone will mind if they get the same camo as a specific unit.

**Review by IllianiCBT — APPROVED** [review]
Thanks for taking a look at this.

LGTM :)

**Pull request merged**
