### PR TITLE
Update Mission.properties

### PR DESCRIPTION
**Pull request by laptopsftw**
Fixed Typo

### CODE REVIEW

**Review by HammerGS — APPROVED** [review]

**Comment by IllianiCBT** [comment]
Sorry the tests took so long to run, GitHub makes us run them manually when a first time contributor pushes a PR.

Welcome to the project! :)

**Comment by IllianiCBT** [comment]
It looks like one of the tests failed, this is likely due to you needing to update the branch on all three repos: mm, mml, and mhq. If you're unsure how let us know and we can likely guide you through it

**Comment by rjhancock** [comment]
Point of note... use branches instead of your master.

**Comment by rjhancock** [comment]
In fact, I'm going to recommend you kill your fork, re-fork, and do the spelling fix in a branch so that any future changes can be done without issues with this main repo if you decide to do anything with your master branch.

**Comment by IllianiCBT** [comment]
I'm going to go ahead and merge this, but I'm going to echo Tex above and _highly_ recommend you avoid working in your master branch moving forward. You really should be using working branches whenever you make edits, even if they're simple ones like this. When things go wrong, Future You will greatly appreciate the extra couple of steps needed to open a working branch.

If you're unsure how, pop a question in the coding help channel of our discord and one of us would be happy to guide you through it :)

**Pull request merged**
