### PR TITLE
Display KIAs on scenario resolution UI

### PR DESCRIPTION
**Pull request by Qwertronix**
Throwing this up here for discussion and suggestions. 

There are a number of cases where a pilot or crewmember or other person might die on the battlefield or during scenario resolution that bypass the usual "6+ hits = dead" rule. Some examples are random rolls when multi-crew mech cockpits are destroyed or when calculating infantry casualties. Generally these would set the hits count of the person to 6 anyway, but also set a `forceDead` flag. 

This `forceDead` thing was not shown to the player and was never modified again later after the ResolveScenarioWizardDialog is launched. This meant that a player modifying the hits slider from 6 to 3 would still find that person sent to KIA rosters, unassigned, logged as dead, and processed through all other things that happen when McCoy shakes his head. 

I've considered the option of simply setting this to false whenever the user modifies the hits slider to something below 6, but what if the slider is changed to another value different than 6 by some other competing calculation before the wizard dialog is displayed? We then end up with a situation where a person has 2 hits shown (which seems fine to the user), remains unchanged, but ends up KIA still after the report. 

The two alternatives seem to be to either drop this whole `forceDead` thing altogether, and replace it with `setHits(HITS_DEAD)`, or show it to the user and give them control. The changes in this PR are for the latter just in case this should be kept around for something else I'm unaware of. Deleting `forceDead` instead would be fairly trivial. 

If we keep the display/UI option, a sub-question would be: What's a good general term to use there? I've put "Forced Death" but I don't like it.

### CODE REVIEW

**Comment by Qwertronix** [comment]
As an aside, this is something I found while trying to fix #464 and #324, but nothing proposes here would actually fix the root cause of those issues.

**Comment by NickAragua** [comment]
Can you post a screenshot of what this looks like?

**Comment by Qwertronix** [comment]
Sure, looks like this: 

image

**Comment by Qwertronix** [comment]
Following some discussion, changed it to be a general KIA checkbox that simply controls whether the person is dead or not, making it no longer controlled by the hits slider. 

Looks like this now: 

image

So far this is only the UI changes with no cleanup of the data handling in the background yet.

**Pull request merged**
