### PR TITLE
Refactored autoAwards Kill Handling for Improved Reliability

### LINKED ISSUE #4514: [0.50.0-SNAPSHOT] AutoAward misinterprets TOE for formation kills
### Environment
15:48:19,393 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:143) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-07-27T01:16:03.359732465
    Today: 2024-07-29
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MegaMek: 4 GB
    MM Code Revision: e86f08fde087d229498e46e9697a41466897653e
    MML Code Revision: bea7884b61319d3b2c803a0fa65988008638e6ef
    MHQ Code Revision: 12c84d7d4a3a993ac643cdf58ba9b621a907170c
    
### Description
When running AutoAwards, formation kill awards are given out to units that do not qualify as being part of the formation. 
This includes units qualifying for lance kills outside their lance, company kills outside their company, etc. 

This can easily be observed when looking at infantry and aerospace support units that are getting kill qualifiers despite being two - three forces separated, even when observing strict individual unit < lance < company < battalion < regiment force containers across the TOE. 

image

### Files
[CampaignSave.zip](https://github.com/user-attachments/files/16414852/CampaignSave.zip)
[custom mechfiles.zip](https://github.com/user-attachments/files/16414872/custom.mechfiles.zip)

### PR DESCRIPTION
**Pull request by IllianiCBT**
### Requires #4573, merge order unaffected

Rewrote how autoAwards handles lifetime and mission-based kills to more reliably read the TO&E and with a mind to reducing the amount of parses made across both the TO&E and when retrieving kills from a force.

This takes advantage of our new TO&E reading functionality, which allows users to better handle non-traditional TO&E layouts - for example, TO&Es in which the deepest formation is not a lance, but is actually a company.

### Closes #4514

### CODE REVIEW

**Comment by repligator** [comment]
New campaign. I forgot to actually turn on auto-awards until part way through the first mission. All the kills were cheesed by using GM mode to change the weather to an F4 tornado and manually assigning them after the scenario. Everything looks fine to me, but I've attached the logs/save in case you want to look them over.

[mekhq.log](https://github.com/user-attachments/files/16475168/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/16475169/megamek.log)
[KillAwardTest30351227.cpnx.gz](https://github.com/user-attachments/files/16475176/KillAwardTest30351227.cpnx.gz)

**Comment by IllianiCBT** [comment]
Ok, that's a good sign. Fingers crossed this should be good to go.

I'm going to hold off marking this as live until I've got a couple more confirmations, but it passing the 'not immediately breaking' test fills me with some confidence.

**Comment by repligator** [comment]
Different new campaign. I used command line nukes this time instead of tornadoes.

[before-early-completion-TOE-AWARD-TEST30350410.cpnx.gz](https://github.com/user-attachments/files/16480959/before-early-completion-TOE-AWARD-TEST30350410.cpnx.gz)

[mekhq.log](https://github.com/user-attachments/files/16480970/mekhq.log)


When I try to complete the mission early, MHQ freezes. Running in debug mode and setting a breakpoint shows that line 156 of `KillAwards.java` is running over and over, on the same person every time.

person = 0d49973a-2611-454a-ad9c-9329786c6603
parentForce: "A Company"
parentForce: "1st Battalion"

Hitting resume program switches between the company and the Battalion, but the person never changes. If I mute the breakpoint, MHQ freezes, and none of the other breakpoints I set get hit. If I turn the breakpoint back on, it goes right back to the same person, switching between company and battalion.

**Comment by IllianiCBT** [comment]
Flipping this to live. It is no longer in draft.

**Review by HammerGS — APPROVED** [review]

**Pull request merged**
