### PR TITLE
Fixed Random-Camouflage Path Handling for Alternate Directory Format

### LINKED ISSUE #4838: [RFE] Introduce Homebrew Faction Loyalty Module to MekHQ
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is a new feature

### Brief Description *

Currently in MekHQ, whilst the unit develops a reputation following the CamOps ruleset, there is no wider impact to relationships or reputation with individual factions that can be either employers or enemies. This means that each contract is essentially a 'blank slate' with the employer.

This RFE is to add in a new optional module to MHQ. Right now I am not aware of any official rules for building unique reputations with factions. The intent behind this RFE is to add depth to mercenary campaign play, rather than for dedicated faction or pirate play. The idea for this module is heavily inspired by the system in HBSTech.

Implementing this RFE should include:

1. A new Campaign Options section to turn on or off the loyalty/reputation module, and modify any key numbers involved.
2. A new Command Centre report - 'Faction Reputation'
3. A report window, showing positive and negative reputations with each faction present in the universe.
4. 'Breakpoints' at reputation numbers - e.g. friendly, unfriendly, etc. to give feedback to players of their reputation status
5. An over-time trend towards 0 reputation with all factions.
6. Reputation changes from taking contracts for and against factions
7. Reputation changes from winning and failing contracts
8. Impacts from faction reputation on contract terms - higher pay or support %, or modifications made to the contract generation rolls, shown in the contract market window.

Implementing the module could be extended in future by having the breakpoints tie in to more involved unit markets (i.e. factory lines or employer markets are only available at certain breakpoints, or have discounts at certain breakpoints).

The module could also be extended in future with nags/suggestions that at very high or low breakpoints, the player force is eligible for a landhold, or special scenarios (assassination attempts, targeted attacks) could be generated on or off contracts.

Faction reputation could also affect background generation of personnel, or be tied into personnel loyalty and turnover - i.e. a mechwarrior from the Draconis Combine might be disloyal to a unit that is allied to the Federated Suns.

Some possible first pass numbers:

- Taking a low-risk (i.e. garrison, cadre, etc.) contract +5 / -5 (for employer/opfor)
- Taking a high-risk contract +10 / -10
- Contract success +5 / -5
- Contract Partial success +3 / -2
- Contract fail -15 / 0
- Under total salvage % at end of contract +3
- Trend towards 0 per year of 1 point

Some breakpoint suggestions:

Allied - 15% pay/salvage bonus, 10% employer/factory line discount, higher chance of contract spawning?, eligible for a landhold (GM add asset, use optional rules from ATOW/CamOps/IntOps for this)
Trusted - 10% pay/salvage bonus, 5% employer/factory line discount
Friendly - 5% pay/salvage bonus
Neutral - no effect
Unfriendly - -10% pay/salvage
Distrusted - -15% pay/salvage, low chance of being attacked in special scenarios
Hated - -20% pay/salvage OR no chance of contract spawning?, high chance of assassination/attack special scenarios

### MekHQ Suite Version *

0.50 -> Future

### Attach Files

Mock-up of the Reputation Window:
FactionReputationReport

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

### LINKED ISSUE #4895: [0.50.01 Nightly] New contract has no camo or placeholder colour for Allies or Enemies
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When accepting a new contract on a new playthrough, enemy and allied forces generate without camouflage.
Before these would default to basic red/green colour. 
 
image

Attached "camo" folder is a custom camo folder used in an external custom unit folder, provided in case it was related.

### Steps to Reproduce

Can be reproduced easily by creating a new game, and accepting any contracy. 
Edit Mission under the Briefing Tab will show both camouflages as missing.

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[camo.zip](https://github.com/user-attachments/files/17142394/camo.zip)
[mekhq.log](https://github.com/user-attachments/files/17142411/mekhq.log)
[Yakima Test Pilots.zip](https://github.com/user-attachments/files/17142413/Yakima.Test.Pilots.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

### PR DESCRIPTION
**Pull request by IllianiCBT**
Accounted for backslash escape sequences in camouflage file paths to ensure compatibility across different operating systems. Added an alternate root directory constant and updated the path sanitization to replace the alternate format correctly.

### Closes #4895

### CODE REVIEW

**Comment by IllianiCBT** [comment]
This should not be merged until someone on a windows system confirms it is working as intended. [Action](https://github.com/MegaMek/mekhq/actions/runs/11045357479)

This can be tested by starting a new campaign, picking a contract from the market (any contract), and then editing that contract. If camo has been randomly generated then this fix works. If it's showing a red 'X' we need to explore other options.

**Comment by HammerGS** [comment]
Tested the artifact this AM

image


Some oddites in the logs
[megamek.log](https://github.com/user-attachments/files/17148481/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/17148483/mekhq.log)

**Comment by IllianiCBT** [comment]
Can you DM me a save, I want to verify the issue is the same and not something else that just happens to give the same results

**Comment by IllianiCBT** [comment]
QA have confirmed this is working now, so it should be good to merge whenever

**Review by HammerGS — APPROVED** [review]

**Pull request merged**
