### PR TITLE
Fixing the Award Tracker post-Ancestors Removal

### PR DESCRIPTION
**Pull request by Windchild292**
This removes the Ancestors column, which was causing the Awards Tracker to not be able to process the data

### CODE REVIEW

**Comment by NickAragua** [comment]
We use an excel file for actual data somewhere?

**Comment by Windchild292** [comment]
This is a helper file in documents, but it does load data from the campaign file

**Comment by BullseyeSmith** [comment]
@Windchild292, I never meant for the AwardTracker to limit you from making whatever changes need to be made to campaign files in order to make things better.  Were you able to find a way to add the Ancestor data without causing an error in the AwardTracker?  I can change it up to fit a new format if needed.  I have to change it anyways because of the surname tables.

**Comment by Windchild292** [comment]
I was able to change from specifying which to remove to specifying which to keep, which largely allows us to make changes to the XML without causing any issues with the file.

**Pull request merged**
