### PR TITLE
add weight tooltip to tonnage JLabels on the force view

### PR DESCRIPTION
**Pull request by firefly2442**

### CODE REVIEW

**Comment by pheonixstorm** [comment]
Outside of AtB why is this needed?

**Comment by firefly2442** [comment]
It's not, should I add a check to see if AtB is enabled?

**Comment by pheonixstorm** [comment]
That would probably be the best way to do it. I don't think any of the current rules have a set tonnage limit for different lances. Even the formation building rules in CO only sets a limit on the number of X weight class for a given lance which in most cases would push a lances weight well beyond what is in AtB.

**Comment by firefly2442** [comment]
OK thanks.  Yeah I was just thinking it would help people setting up their forces before flipping to the Briefing tab and seeing that what they expected was going to be a light lance ended up being a medium lance for example.

**Comment by firefly2442** [comment]
Tweaked the commit to check if AtB is enabled per request.

**Pull request merged**
