### PR TITLE
Add basic GitHub Actions CI

### PR DESCRIPTION
**Pull request by sixlettervariables**
Mirrors the work for MegaMek and MegaMekLab.

### CODE REVIEW

**Comment by sixlettervariables** [comment]
I've cleaned this up and squashed it all down to the correct bits. Example run here:

https://github.com/sixlettervariables/mekhq/pull/213/checks?check_run_id=560832198

**Comment by NickAragua** [comment]
I'd approve it, but I have no idea what any of these things do, so better for @neoancient to review it.

**Comment by Windchild292** [comment]
I'm in the same boat as the above

**Comment by sixlettervariables** [comment]
I've added comments explaining the bits and pieces. It wasn't immediately obvious to me either, but git rebase hides my shame.

**Comment by sixlettervariables** [comment]
Okay this update to the action includes the following:
1. If there is a "sister" branch on the submitter's MM and/or MML repo, that branch is used, otherwise it uses MM/master and MML/master.
2. Composite builds have been corrected.

**Comment by Windchild292** [comment]
The changes look and sound great based on the comments in the file, however I also don't know the language, so I don't feel comfortable approving this PR.

**Pull request merged**
