### PR TITLE
Check muntions type before replacing missing ammo bin

### PR DESCRIPTION
**Pull request by Bonepart**
Fix for https://github.com/MegaMek/mekhq/issues/455

### CODE REVIEW

**Comment by neoancient** [comment]
I haven't looked at the code for this one yet but I had given it some thought based on what I remember of the class. Would it work to set the ammo type on the cloned replacement? I don't guess it matters much in terms of efficiency but I think the code would be cleaner.

**Comment by Bonepart** [comment]
I tried that first, and it causing it to reload the correct ammo, but in the repair task it still shows as the original ammo type. It basically changed the munition type without changing anything else in the class that usually gets set when it is constructed. So since we are building a new part anyway I just told it to make a new ammo bin instead of cloning the part it found for replacement.

**Comment by neoancient** [comment]
Right. Didn't think of that. This is what comes of figuring out how to do it before you actually look at the code.

**Comment by Bonepart** [comment]
Code wise it doesn't add a whole lot, just an If statement to check type, if they match it clones, if not it generates a new ammo bin

**Pull request merged**
