### PR TITLE
Updated StratCon Sector Sizes & Added Persistent OpFor

### PR DESCRIPTION
**Pull request by IllianiCBT**
We have a lot of plans for StratCon in 2025, so consider this an early Christmas present.

This PR updates the size of StratCon Sectors (Tracks) to be tied to the size of the planet, rather than the number of lances required by the contract.

We also do some under-the-hood changes and expansions to the utility methods used to add scenarios to StratCon maps. These were lifted from the upcoming Logistics Module. A bunch of additional `null` safeguards were put in place, too. So, hopefully, there shouldn't be any major issues.

Finally, I have implemented a persistent OpFor. Now, when you arrive on contract each Sector is pre-seeded with enemy forces. These forces will explore the StratCon map, engaging your forces and facilities. When defeated, each pre-seeded force is permanently removed, though there is the chance that new enemy forces will be redirected into your AO to counter your advance - based on Morale.

Speaking of Morale, while still based on a dice roll, morale is significantly impacted by the number of enemy forces exploring your AO. So you want to make sure to get rid of them quick!

You will still face weekly scenarios as normal.

Scouting no longer spawns enemy forces, so an area already cleared will stay cleared (barring new forces entering the area).

Hype aside, this is a very basic implementation and one designed to be expanded on throughout 2025. Right now enemy forces blindly bumble about the AO until they hit something. The next step will be adding a heat map.

### CODE REVIEW

**Comment by IllianiCBT** [comment]
For anyone curious:

The number of enemy forces spawned is based on enemy faction, quality, and contract type.

We start with a baseline value determined by enemy faction: A Clan Cluster (11 Stars), an IS Battalion (14 Lances), or a ComStar Level IV (18 Level IIs). Note that these values have all been reduced by half. At a later date we plan to have friendly forces appear in the AO too, at which point this artificial reduction will be removed.

We then consult the following table:
Quality F = 0.25
Quality D = 0.5
Quality C = 0.75
Quality B = 1.0
Quality A = 1.5
Quality A* = 2.0

We adjust this value by the contract type:
Pirate Hunting = 0.5
Garrison Type = 0.5 (Garrison Duty, Cadre Duty, Security Duty, Riot Duty)
Offensive = 1.0 (Diversionary Raid, Objective Raid, Recon Raid, Extraction Raid, Guerrilla Warfare)
Planetary Assault = 2.0

These values are then used as a modifier to adjust the initial value (rounded up)

**Example A**
Commander Romanova is deploying for a contract against Clan Ghost Bear. The information provided by her employer rates the enemy forces as _C_ and the contract is categorized as an _Objective Raid_.

That means Commander Romanova can expect the Regulars to deploy 9 forces of varying sizes (11 * 0.75). This might seem like a lot, but it's important to note that these forces do not all need to be fought, and certainly not all at the same time.

**Example B**
Commander Steve Rogers is deploying for a contract against the Draconis Combine. The information provided by his employer rates the enemy forces as _B_ and the contract is categorized as _Garrison Duty_.

That means Commander Rogers can expect the DCMS to deploy 14 forces of varying sizes (14 * (1 * 1)).

**Example C**
Star Colonel Fury is deploying for a mission against Clan Wolf. The information provided by the Clan Watch rates the enemy forces as _A_ and the mission is categorized as _Planetary Assault_.

That means Star Colonel Fury can expect Clan Wolf to deploy 54 forces of varying sizes (18 * (1.5 * 2)). This is going to be a tough fight!

**Comment by Dark-Hobbit** [comment]
Shouldn't example B be 7 forces because it's a Garrison Duty? (14 * (1 * 0.5))

**Comment by IllianiCBT** [comment]
Yes

**Comment by IllianiCBT** [comment]
Pushed an update to fill in a couple of holes:

- Morale has been updated to offer a more consistent experience. In particular, we want clearing out enemy forces from Sectors to have an impact on morale
- Garrison contracts no longer feel like a constant planetary invasion.

### Closes #4565

**Pull request closed without merging**
