### PR TITLE
Issue #785 SLDF Ranks are Wrong

### LINKED ISSUE #785: SLDF Ranks Are Wrong
The ranks for the SLDF are wrong. They didn't have Lieutenant JG and Lieutenant SG. They just had Lieutenant. Warrant Officer is also missing from the list of ranks.

### PR DESCRIPTION
**Pull request by jschmetzer**
Fixes #785. Adds 2nd Star League rank set, edits default Star League rank set to remove two lieutenants, add warrant, per FM: SLDF

### CODE REVIEW

**Comment by HammerGS** [comment]
The data part looks good to me and the code does as well.

**Comment by Windchild292** [comment]
This won't migrate properly.

**Comment by jschmetzer** [comment]
Whoops. Figures I'd mess up my first one. 👍

**Comment by Windchild292** [comment]
Just edit in progress is fine. There's also a type on the static constraint :)

**Comment by jschmetzer** [comment]
Doh. There it is right there, glowing at me in Atom. 

Would that have caused the fail or should I rearrange as requested, too?

**Comment by Windchild292** [comment]
That caused the fail, the rearrange will likely cause issues on existing games if it is not done

**Comment by Windchild292** [comment]
This will cause a few other issues due to internal use of RS_SL... you could swap RS_SL to RS_FSL and keep the SSL as SL, or you'd need to do internal fixes in five or six locations.

**Comment by jschmetzer** [comment]
Does the name string need to remain original as well, or could RS_SL = Second Star League?

**Comment by Windchild292** [comment]
Not localized, and we currently handle SL as Second Star League. I'd say it is fine?

**Review by Windchild292 — APPROVED** [review]

**Pull request merged**
