### PR TITLE
Add founder on personnel filter groups

### LINKED ISSUE #1888: Personnel Type of founders on Personnel tab
### Environment
Ver 0.47.7

### Description
You can check the list of dependent, then why not founders?

### PR DESCRIPTION
**Pull request by binaryspica**
Resolves #1888. I hope that it works....

### CODE REVIEW

**Comment by binaryspica** [comment]
> Because of current implementation the changes will also require implementation in the PersonnelMarketDialog file

Isn't it only affects market? Else it is just for the consistency?

**Comment by Windchild292** [comment]
Consistency and because of how the current implementation is (although it is on my list to fix this issue)

**Comment by binaryspica** [comment]
> Consistency and because of how the current implementation is (although it is on my list to fix this issue)

Got it!

**Comment by Windchild292** [comment]
Looking better, but missing the strings under PersonnelMarketDialog::getPersonnelGroupName

**Comment by binaryspica** [comment]
Done. Is there anything left?

And it seems the reason why the market's personnel type have two last sections with '?'.

**Comment by Windchild292** [comment]
Nothing else I can see, and that would be why.

**Pull request merged**
