### PR TITLE
Fix for Issue #113 - MekHQ 0.3.29 Dates are cut off in Personnel log …

### PR DESCRIPTION
**Pull request by wildj79**
…display

This is a fix for Issue #113.  This only seemed to be affecting Mac OSX. The default font, Lucida Grande in this case, seems to render wider on OSX than it does on other OS's. The solution is to widen the column slightly to accomodate the wider font.  Will need to test that this doesn't have an adverse effect on other OS's.

### CODE REVIEW

**Comment by wildj79** [comment]
screen shot 2016-07-29 at 12 10 59 am

**Comment by pheonixstorm** [comment]
You may want to shrink the log body by 10 points or make sure the kill log table and the section above the log is the same size (I don't know if it was changed to a table as well). If the size is the same for all four sections there should be no issue. The fourth I forgot to mention above is for the persons bio.

**Comment by wildj79** [comment]
I actually thought about that after I issued the pull request :wink:. I'll make the change and push it back into my fork.

**Comment by wildj79** [comment]
I've been able to test this on my Windows box, it doesn't seem to have any adverse effects. I'll try testing it on my Debian box later to see if these changes have any adverse effects on Linux.

**Comment by wildj79** [comment]
Closing this so I can resubmit it the correct way: create a new branch and open a pull request with that, so I can keep master in sync with the upstream repo 😑. Live and learn.

**Pull request closed without merging**
