### PR TITLE
AbstractIcon: Force Icon Rework

### LINKED ISSUE #347: Feature Request:TOE Layered Icon Changes
Three simple requests in one;

#1 In the XML file for the campaign the items selected on each layer are stored in the XML file. Can a change be made to the Change Force Icon context menu code so that when the dialog opens, the _currently selected layers_ are pre-populated? Currently if you build a layered icon then edit the layered icon you have to start from scratch again. (This is aggravating if you have a 4 or 5 layer icon and just needed to tweak the Formation, or whatever, you have to go from tab to tab rebuilding the icon from scratch)

#2 A "none" selection in each tab for building the layered icon. Currently if you accidentally click/tap a section (such as select a background image) there is no way of clearing that out other than starting all over again.

#3 Add "Copy Icon" to the context menu and "Paste Icon" to the context menu on the TOE page. This would allow you to more quickly build a TOE by copying an icon from one force to another. 

These three things would rapidly accelerate the TOE building process for larger forces. I'm running a campaign where there are four regimental sized units on the planet plus air wing and associated other units, and it took 8 hours just to build the icons for the TOE on the units. :)

### LINKED ISSUE #354: Feature Request- Layered TOE Icon expansion
Specifically, could we have the options presented as canon in the ... I think it was CampOps?

The things missing are: left-side letters............ and a few things I'm forgetting. Maybe LAMs Mech+star and Battle Armor's shaded X. I don't remember seeign those. Unfortunately I have to run very soon, and I wanted this up before I forgot. :)

### LINKED ISSUE #2235: medical.png in data>images>force>Pieces>Type needs to be renamed to Medical.png
### Environment
47.11
Windows 10
Java version 8 build 271 (build 1.8.0_271-b09)

### Description
In the TO&E screen, when creating force icons using the "layered" option, the medical.png does not show up as an option. However, after I noticed that all the other pngs were named with capitals at the front, I renamed it to Medical.png. It now shows up, and I can use it in the TO&E icons.

### Files
Provide the .cpnx campaign file that this issue occurs in.

[Burg's Brigade30251025x.cpnx.gz](https://github.com/MegaMek/mekhq/files/5558415/Burg.s.Brigade30251025x.cpnx.gz)

### LINKED ISSUE #2448: Vehicle Tracked Force Icon is weirdly interacts with the other icon parts.
### Environment
Ver 0.47.17

### Description
r1
As you see, if I try to make the armored artillery icon, the circle of artillery icon and the oval of armor icon are overlapped.

It must be looks like that;
600px-Military_Symbol_-_Friendly_Unit_(Solid_Light_1 5x1_Frame)-_Artillery_-_Mechanized_(NATO_APP-6) svg

Also it seems that the others are also overlapping with the same tracked one. Also tracked small and artillery all have the same problem. I think that the oval must be bigger, as well as adjust the point of the items in adjustments tab.

### PR DESCRIPTION
**Pull request by Windchild292**
This PR moves Force Icons to Abstract Icon, and divides them into three separate types. These are StandardForceIcon, LayeredForceIcon, and UnitIcon, all of which have differing functionality. Additionally, this adds LayeredForceIcon export to png, force icon TO&E icon copy/paste, and automated new day force icon operational status updates (based on a MekHQ option).

This PR also replaces the Force Icon images with the far more comprehensive and standardized Kailan pack, with full migration from the old setup and a new MekHQ extras repository containing the current pack and a pack of standard force icons created by Mjolnir06.

The full list of what this does, which I used to keep this organized:
- [x] Move Force and Layered Icons to Abstract Icon
- [x] Make the Unit Icon its own thing
- [x] Force Icon Data Swapover to Kailan Pack
- [x] Standard Force Icon migration to Layered Pieces
- [x] Layered Force Icon migration to new Layered Pieces
- [x] Unit Icon migration
- [x] New Standard Force Icon Dialog
- [x] New Layered Force Icon Dialog
- [x] New Unit Icon Dialog
- [x] GM Tools Force Icon Creation
- [x] Layered Force Icon Export
- [x] Create MekHQ Data Repository
- [x] Fixes #347: TO&E Force Icon Copy/Paste
- [x] Fixes #354
- [x] Fixes #2235
- [x] Fixes #2448
- [x] Fixes the flattened AbstractDirectory Setup by reworking it to no longer be flattened (required for the changes to work)
- [x] Removes the broken AbstractDirectory Zip Setup (required for the changes to work)
- [x] Swaps AbstractIconChooser to AbstractPanel
- [x] Adds Automated Force Icon Operational Status on New Day

For reviewers:
This file is large because of the ~7k lines of migration, and almost all of the file differences are because of the Force Icon pack swapover. Code-wise most of the work is on the dialog-side, to get the three icon types (with the fourth, internal type used in LayeredForceIcon) selectable and usable.

### CODE REVIEW

**Comment by HammerGS** [comment]
Kinda like to see this one in for 49.6. But I can't even filter to see the changed code. It crashes Chrome for me. How about two separate PR's one for the data stuff and one for the code. 

Otherwise I think this will never happen.

**Comment by Windchild292** [comment]
I'd have separated the two if they weren't mutually required. As for GitHub's handling... that's annoyingly bad code on their end.

**Comment by NickAragua** [comment]
Bottom line is, there is no way to meaningfully review the code changes. Feel free to spin out a separate PR with just the code changes for review purposes only.

**Comment by Windchild292** [comment]
I've opened #3014, which is just the code for this PR.

**Pull request merged**
