### PR TITLE
[Bandaid] Added Dialog to Confirm New Campaign

### PR DESCRIPTION
**Pull request by IllianiCBT**
### Current Implementation
Currently the option to start a new campaign is available through 'toolbar/files/new campaign' and is listed immediately beneath Save Campaign and Load Campaign.

### Problem
I am aware of a long standing bug where clicking 'new campaign' and then cancelling out can have adverse effects on a campaigns' 'campaign settings'. The proximity of the option near 'save' and 'load' increases the chances of a user accidentally interacting with 'new campaign'. In these events, the user will naturally cancel out of the option and (unless they're on Discord a lot) they will likely be unaware of the damage this potentially caused.

### Solution
This has been a problem for years at this point, while the issue being fully resolved is the more desirable outcome, this patch is designed to reduce the chance of users accidentally clicking 'new campaign' when attempting to save or load.

### Update
Since the initial introduction of this PR I have significantly changed its implementation.

When selecting 'New Campaign' users will be presented with a dialog asking them to confirm that they wish to start a new campaign. Selecting 'no' or closing the dialog does nothing. Selecting 'yes' initiates the new campaign process (this process is identical to current implementation).

image

### CODE REVIEW

**Comment by IllianiCBT** [comment]
> What would be the order with New Campaign moved down?

image

**Comment by HammerGS** [comment]
What about on the splash, my understanding is that is another big source of issues. But I do think Load, Save, New might be a better order as it's easy to hit new campaign if you go for exit. Creating a new campaign that triggers the exit process

**Comment by IllianiCBT** [comment]
> What about on the splash, my understanding is that is another big source of issues. But I do think Load, Save, New might be a better order as it's easy to hit new campaign if you go for exit. Creating a new campaign that triggers the exit process

The splash is unchanged, I'm not aware of any issues caused by that, but even if there were I don't think we could change the order without reducing usability.

image

I do see your point about placement by 'exit'. I didn't consider a situation where a user goes to click 'exit', hits 'new campaign', exits out of that dialog, clicks 'exit' and then saves their campaign.

Alrighty, with that in mind... I'm really struggling to find somewhere we can move 'new campaign' to where there is no risk of it being clicked accidentally. Any suggestions? Because my mind is blank.

**Comment by HammerGS** [comment]
I think I'm changing my vote to remove it completely option.

**Comment by SuperStucco** [comment]
Better isolation can be had by pushing the actual element into a flyout e.g. "New Campaign > Start New Campaign..."  This lets it live next to the save/load elements while stopping it from accidental use.

**Comment by IllianiCBT** [comment]
### Update
Since the initial introduction of this PR I have significantly changed its implementation.

When selecting 'New Campaign' users will be presented with a dialog asking them to confirm that they wish to start a new campaign. Selecting 'no' or closing the dialog does nothing. Selecting 'yes' initiates the new campaign process (this process is identical to current implementation).

image

**Comment by IllianiCBT** [comment]
I'm aware of the unusually large number of dirty edits on this PR. I just spotted them and will fix tomorrow.

**Comment by IllianiCBT** [comment]
Too many dirty edits. I know how I did them, so easy to avoid in the future, but for the sake of my sanity I'm just going to redux this PR.

**Pull request closed without merging**
