### PR TITLE
Fix 3880 cannot refit clan mechs due to renames

### LINKED ISSUE #3880: [0.49.18] MekHQ mech customisation in Mek Lab fails on Clan mechs
### Environment
What version of MekHQ does your issue apply to? 0.49.18 Development
What operating system are you using?  Windows 11 10.0
What java version are you using?  17.0.10

### Description
Started a fresh campaign, added some mechs and attempted to customise a clan mech from within MekHQ via Hangar > Customize > Customize in Mek Lab. After making changes such that the Begin Refit button was enabled, I clicked Begin Refit and am given the error here:
image

mekhq.log gives the following, as an example:
```
mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1586) - Could not read back refit entity Masakari B
megamek.common.loaders.EntityLoadingException: Could not load Masakari B from the mech cache
	at mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1578)
	at mekhq.campaign.parts.Refit.begin(Refit.java:976)
	at mekhq.gui.CampaignGUI.refitUnit(CampaignGUI.java:1637)
	at mekhq.gui.MekLabTab.lambda$initTab$0(MekLabTab.java:122)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

12:46:32,045 WARN  [mekhq.campaign.parts.Refit] {AWT-EventQueue-0}
mekhq.campaign.parts.Refit.saveCustomization(Refit.java:1590) - Deleting invalid refit file data\mechfiles\customs\Orwell Heavy Rifles\Masakari B.mtf
```

I have replicated this error on three Clan mech chassis (Ryoken, Mad Cat, Masakari) but the refit goes ahead normally on an IS mech (Centurion).

### Files
[Orwell Heavy Rifles30620101.cpnx.gz](https://github.com/MegaMek/mekhq/files/14572655/Orwell.Heavy.Rifles30620101.cpnx.gz)
[megamek.log](https://github.com/MegaMek/mekhq/files/14572662/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14572663/mekhq.log)

### PR DESCRIPTION
**Pull request by Sleet01**
This should fix both Clan configuration changes and custom refits.
Edit: also fixes an NPE when all Techs are occupied and the user wants to start a Refit.

The problem is obviously the requirement to include the Clan unit name in parentheses when doing Clan unit lookups.

I am open to refining this fix further, such as:
- Adding a Clan-aware lookup _within_ the unit cache
- Further refining the new utility function so that it can return the filtered list of alternate configurations required by the Refit/Configuration... chooser
- Figuring out a faster fuzzy search that will return all matching units (possibly by changing the namesMap to a BTree or something)
- Adding new tests to verify more Clan configs work correctly with Refits,

but this fix works now, and I don't have time to do any more for probably a week.

Testing:
- Verified fixed issues reported in #3880 
- Ran all three projects' unit tests
- Added new unit test covering Masakari A->B conversion (this doesn't test the names issue, but was a hole in our testing)

Close #3880

### CODE REVIEW

**Comment by Sleet01** [comment]
Converted to draft due to CI failures.  Will clean up in a bit.

**Comment by Sleet01** [comment]
Tests broken after pulling latest Planetary Conditions code; should be fixed by MegaMek/mekhq/pull/3834

**Comment by SJuliez** [comment]
Thanks for dealing with the clan name thing.

**Comment by Sleet01** [comment]
> Thanks for dealing with the clan name thing.

There may be some other spots where we'll want to replace `getChassis()` with `getFullChassis()` but I figure that can be a separate PR.

**Review by NickAragua — APPROVED** [review]

**Pull request merged**
