### PR TITLE
Added meaningfull names for new AtB contracts.

### PR DESCRIPTION
**Pull request by aunoor**
Replace default "New contract" with some meaningfull description for contracts from Contract Market.

### CODE REVIEW

**Comment by pheonixstorm** [comment]
You might want to include more as this could lead to contracts containing the same name, something which HQ does not allow. The majority of people rename the contract before accepting it though.

Also, if I am reading this right it looks like things will be jumbled together as well. Might want to add a separator so it would look like FedSun-year-missiontype, though I would suggest Faction-mmyy-missiontype (FedSuns-0325-Objective Raid). Optionally you could add the duration to make tracking the end date a bit easier. ie Faction-mmyy-mission-duration (FedSuns-0325-Raid-03)

**Comment by Dylan-M** [comment]
Actually the ideal format would be:
Federated_Suns_30650317_Raid_03

In other words, full ISO standard date format and underscores for separators.

**Comment by purpledragon2** [comment]
I would love to see this.  For Unit historical sake I would include the name of the planet in there somehow.

**Comment by pheonixstorm** [comment]
The name of the planet is already in the contract itself, I don't think it would be useful personally but that's up to ralgith.

**Comment by aunoor** [comment]
HQ allow to contracts have same names. Hungreds of contracts with "New contract" name is user problem only. :)
Underscore as separators is bad idea, I think. From other variants, variant from @pheonixstorm is more likely for me.
But, I don't vew method to shorten names of factions and mission types. Then generated contract name may be very long, ex.: "Federated Suns-306503-Objective Raid-03"

**Comment by pheonixstorm** [comment]
Then the only contracts able to do so are atb contracts which should be fixed. At least for ACCEPTED contracts. For the contract generator I don't think it matters what the name is. Yes the name might be a bit long but there isn't much to shorten it. For naming my contracts I use the 2-letter faction code, though the format is a bit different. ie FS-Garrison-18-0325

**Comment by aunoor** [comment]
May be use hardcoded to source faction code instead full name? "FRR" instead "Free Rasalhague Republic" maybe will be much better?

**Comment by pheonixstorm** [comment]
There should be a function to call the short name for the factions, though I have never looked so no clue where it might be.

**Comment by aunoor** [comment]
Please close this request as obsolete.

**Comment by Akjosch** [comment]
You can close your own PRs and tickets ...

**Pull request closed without merging**
