### PR TITLE
Display Advanced Medical Injuries in UI

### PR DESCRIPTION
**Pull request by WeaverThree**
The numerical hit counter in the force display in the TO&E and the injuries column in the Personnel tab were both only showing "hits" from when advanced medical is turned off. This fixes them so they work with both systems. Are there any other places I need to hit with this?

### CODE REVIEW

**Review by IllianiCBT — APPROVED** [review]

**Comment by HammerGS** [comment]
This has picked up conflicts.

**Comment by IllianiCBT** [comment]
Just a thought while you fix these conflicts, it might be useful to have fatigue displayed in the TO&E, too.

You'll want something that looks like this:

```
if ((campaign.getCampaignOptions().isUseFatigue()) && (person.getEffectiveFatigue(campaign) > 0)) {
        int effectiveFatigue = person.getEffectiveFatigue(campaign);
        ++ colored text code ++
}
```

**Comment by WeaverThree** [comment]
Not sure why that was a conflict, it was in a separate part of the file.



It doesn't look great unless you expand the panel, but then, neither do their names.

**Comment by IllianiCBT** [comment]
Could we perhaps arrange it so that its...

> <Name>
> <Veterancy and Role>
> <Injuries/Hits and Fatigue>

...I don't know if that would look better.

**Comment by HammerGS** [comment]
> Now it's like this:
> 
> 

I prefer this.

**Comment by IllianiCBT** [comment]
LGTM

**Pull request merged**
