### PR TITLE
Parts - minor refactoring and better information

### PR DESCRIPTION
**Pull request by WeaverThree**
This is a fairly hefty scrub and tuning of campaign/parts/\*.java, particularly the string and UI-related bits. It fixes a number of minor bugs and nuisances as it goes.

Original Goal:

- Display unit tonnage of parts that it matters for (locations, sensors, jump jets, MASC, etc) prominently in the repair bay and generally enhance the repair experience.
- Display available stores on replacement items so you know if you're using the last one on a repair and such.
- Get any other useful information in front of the user.

Major points:

- Parts now rely more on their parent (usually Part) for getDetails information, some of them losing their own implementation completely.
- More robust generic getDetails in major classes, particularly Part
- This ends up fixing or improving the shop descriptions of numerous items as well
- General code cleanup of campaign/parts/\*.java, especially regrading string handling functions.

Along the way:

- Only show damage on parts that are actually damaged
- Turrets and Rotors now show the tonnage they're for
- Turrets now get said tonnage applied properly in the parts store
- Superchargers now show all their relevant stats in empty omnipods.
- Superchargers in omnipods are now the correct price instead of way cheaper (missing zero in math).
- Empty omnipods now show the tech base of the part they're made for.
- Make missing parts display how many you have in stock and make the display of transit parts nicer there.
- Updated deprecated campaign.getPart()s in PodSpace
- Update lots of things to use ReportingTools and StringBuilders
- Drop Part.getOrderTransitStringForDetails because this is also done by a function in PartInventory, changed the places it was used to the other one.
- Some pluralization tweaks and other minor grammar stuff.
- Show parentheses around item details on Command Center tab.
- Mek locations show cost now too; minor cost function refactoring.
- Show Tech SPAs on the Tech Panel. Probably should have been a separate PR but got mixed in here and I don't know how to separate it.

There isn't a whole lot to see but here are a few examples of stuff that you can:

### CODE REVIEW

**Comment by WeaverThree** [comment]
I'll sort out the failed test after this headache x.x

**Comment by WeaverThree** [comment]
I fixed the tests for the new format of MekLocation details (mainly, adding tons and leaving off damage unless damaged). This also led me to some other errors I had made with that one, which are now fixed.

I also realized that I had not gotten to PodSpace's getDetails, and I also stumbled into something that regexes the resulting string in TaskTableModel, so I'm not touching that for now. I haven't played with omnimechs and I do not understand how pods work very well from my experiments.

**Review by IllianiCBT — COMMENTED** [review]
I don't know enough about the systems being touched to review this. So it might be in the queue for a little longer than normal.

**Comment by WeaverThree** [comment]
Found one thing I missed, mek locations need to show their repair costs as well. Not that these values are relevant to any game situations given the scale of money, all parts should show it if they have it.

**Comment by WeaverThree** [comment]
I ran into an issue, and fixed it ^^

**Review by HammerGS — APPROVED** [review]
Tested and seems to work.

**Pull request merged**
