### PR TITLE
#2927 Fixed Spectral Types for Abadan, Tellman's Mistake, Maxwell, Ga…

### PR DESCRIPTION
**Pull request by UrsKR**
…listeo, Loongana, Remulac

Data from
https://www.sarna.net/wiki/Abadan
https://www.sarna.net/wiki/Tellman%27s_Mistake
https://www.sarna.net/wiki/Maxwell
https://www.sarna.net/wiki/Galisteo
https://www.sarna.net/wiki/Loongana
https://www.sarna.net/wiki/Remulac

### CODE REVIEW

**Comment by HammerGS** [comment]
Hi. We don’t consider Sarna a canon source. We’d need data confirmed from the books themselves.

**Comment by UrsKR** [comment]
That's too bad, since I do not have access to all the sourcebooks and fiction.
I can confirm the data on **Maxwell** and **Tellman's Mistake** from the old FASA House Marik sourcebook, the data on **Galisteo** from the novella The Calm of the Void. 
Also, I have now purchased the Dark Age novel Hunters of the deep and can confirm the data on Remulac. I have also purchased the CGL sourcebook Objectives:FWL to confirm the data on Abadan.

Although given as a source, the book lists a different rating for Loongana than listed on sarna.net. I will update the PR.

**Comment by UrsKR** [comment]
Loongana's spectral type now conforms to CGL's Objectives:FLW sourcebook.

**Comment by UrsKR** [comment]
FWIW, also changed the page on sarna.net to avoid future confusion.

**Pull request merged**
