### PR TITLE
Migrating to MavenCentral from JCenter

### PR DESCRIPTION
**Pull request by Windchild292**
JCenter is shutting down in February.

### CODE REVIEW

**Comment by Windchild292** [comment]
I have no clue as to why this is failing when the MegaMekLab CI/CD is successful.

I'll investigate more when I'm less tired, but... it's just odd.

**Review by NickAragua — APPROVED** [review]

**Comment by HoneySkull** [comment]
All my gradle commands fail unless I change this line back to jcenter().  Not sure why... but I get the same error from my local gradlew command locally as the nightly build on github.

**Comment by NickAragua** [comment]
I wonder if it's because there's a dependency on the megamek/mml repos in MekHQ. Are you having the same problem building just plain megamek?

**Comment by HoneySkull** [comment]
No - the MegaMek repo gradle commands are fine.  I'm mentioning it because it's complaining about the same line in the build.gradle file as I see in the nightly error logs.  I think it's the same error.

**Comment by Windchild292** [comment]
MML builds fine both locally and online, MHQ build fine locally for me, but this apparently breaks in MHQ-integrated MML builds. I'm wondering if this is the same delayed response we saw with the version changes, but this time it breaks things rather than hides missing internal code changes.

I do have a fix idea, but can't test until tomorrow

**Pull request merged**
